package Presentation;

import Bussiness.PlayerManager;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;

public class InsertPlayers extends javax.swing.JFrame {

    private PlayerManager playerMan = new PlayerManager();
    public InsertPlayers() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        initialConfig();
        
        restart();
    }

    public int isInteger(String numberString) {
        try {
            return Integer.parseInt(numberString); 
        } catch (NumberFormatException e) {
            return -1;
        }
    }
    
    public void fillComboBoxes(JComboBox comboToFill, ArrayList<String> filling) {
        for (int item = 0; filling.size() > item; item++) {
            comboToFill.addItem(filling.get(item).toString());
        }
    }
    
    public void initialConfig() {
        fillComboBoxes (cbTeams, playerMan.getTeams() );
        fillComboBoxes (cbProfile, playerMan.getProfile() );
        fillComboBoxes (cbFortitude, playerMan.getFortitude() );
    }
    
    
    public void restart() {
        inputID.setText("");
        inputName.setText("");
        inputAge.setText("");
        radioBtnState.setSelected(false);
         
        Date date = playerMan.restartDate();
        dateDebutDate.setDate(date);

    }
    
    public void addPlayer() {
        int playerID = isInteger( inputID.getText() );
        int playerAge = isInteger( inputAge.getText() );
        String name = inputName.getText();
        boolean state = radioBtnState.isSelected();
        int team = cbTeams.getSelectedIndex();
        String profile = cbProfile.getSelectedItem().toString();
        String fortitude = cbFortitude.getSelectedItem().toString();
        
        Date inputDate = dateDebutDate.getDate();
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        Date date = playerMan.restartDate();
        try {
            date = format.parse(inputDate.toString());
        } catch (ParseException ex) {
            Logger.getLogger(InsertPlayers.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if (playerID > -1 && playerAge > -1 && !name.equals("")) {
            playerMan.insertPlayerInDB(playerID, name, playerAge, state, team, profile, fortitude, date);
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dateDebutDate = new com.toedter.calendar.JDateChooser();
        inputID = new javax.swing.JTextField();
        inputName = new javax.swing.JTextField();
        inputAge = new javax.swing.JTextField();
        radioBtnState = new javax.swing.JRadioButton();
        cbFortitude = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cbProfile = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        cbTeams = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuInsert = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        menuReport1 = new javax.swing.JMenuItem();
        menuReport2 = new javax.swing.JMenuItem();
        menuReport3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Hiragino Sans", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(20, 20, 20));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Fecha de debut:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 150, -1));

        jLabel4.setFont(new java.awt.Font("Hiragino Sans", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(20, 20, 20));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Bienvenido al registro de jugadores");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 900, -1));

        jLabel5.setFont(new java.awt.Font("Hiragino Sans", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(20, 20, 20));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Cédula:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 140, -1));

        jLabel6.setFont(new java.awt.Font("Hiragino Sans", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(20, 20, 20));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Primer nombre:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 140, -1));

        jLabel7.setFont(new java.awt.Font("Hiragino Sans", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(20, 20, 20));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Edad:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 140, -1));

        jLabel8.setFont(new java.awt.Font("Hiragino Sans", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(20, 20, 20));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Estado:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 140, -1));

        jLabel9.setFont(new java.awt.Font("Hiragino Sans", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(20, 20, 20));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Fortaleza:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 140, -1));

        dateDebutDate.setBackground(new java.awt.Color(204, 204, 204));
        dateDebutDate.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(dateDebutDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 180, 30));

        inputID.setBackground(new java.awt.Color(204, 204, 204));
        inputID.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        inputID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIDActionPerformed(evt);
            }
        });
        jPanel1.add(inputID, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 180, 30));

        inputName.setBackground(new java.awt.Color(204, 204, 204));
        inputName.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        inputName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNameActionPerformed(evt);
            }
        });
        jPanel1.add(inputName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 180, 30));

        inputAge.setBackground(new java.awt.Color(204, 204, 204));
        inputAge.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        inputAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAgeActionPerformed(evt);
            }
        });
        jPanel1.add(inputAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 180, 30));

        radioBtnState.setFont(new java.awt.Font("Hiragino Sans", 0, 18)); // NOI18N
        radioBtnState.setForeground(new java.awt.Color(20, 20, 20));
        radioBtnState.setText("Activo");
        jPanel1.add(radioBtnState, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, -1, -1));

        cbFortitude.setBackground(new java.awt.Color(204, 204, 204));
        cbFortitude.setFont(new java.awt.Font("Hiragino Sans", 0, 18)); // NOI18N
        cbFortitude.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(cbFortitude, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 180, -1));

        jLabel11.setFont(new java.awt.Font("Hiragino Sans", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(20, 20, 20));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Perfil:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 140, -1));

        cbProfile.setBackground(new java.awt.Color(204, 204, 204));
        cbProfile.setFont(new java.awt.Font("Hiragino Sans", 0, 18)); // NOI18N
        cbProfile.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(cbProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 180, -1));

        jLabel12.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 1, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(20, 20, 20));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Información General");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 340, -1));

        jLabel13.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 1, 22)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(20, 20, 20));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText(" Destreza");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 340, -1));

        btnAdd.setBackground(new java.awt.Color(0, 153, 153));
        btnAdd.setFont(new java.awt.Font("Hiragino Sans", 0, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(0, 0, 0));
        btnAdd.setText("Añadir");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 450, 180, 40));

        cbTeams.setBackground(new java.awt.Color(204, 204, 204));
        cbTeams.setFont(new java.awt.Font("Hiragino Sans", 0, 18)); // NOI18N
        cbTeams.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(cbTeams, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 180, -1));

        jLabel10.setFont(new java.awt.Font("Hiragino Sans", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(20, 20, 20));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Equipos");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 140, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 560));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(245, 245, 245));
        jLabel1.setText("Pamela Murillo Anchia");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 130, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 900, 40));

        menuInsert.setText("Insertar");
        menuInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInsertActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuInsert);

        jMenu1.setText("Reportes");

        menuReport1.setText("Velocidad");
        menuReport1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReport1ActionPerformed(evt);
            }
        });
        jMenu1.add(menuReport1);

        menuReport2.setText("Debut");
        menuReport2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReport2ActionPerformed(evt);
            }
        });
        jMenu1.add(menuReport2);

        menuReport3.setText("Activos");
        menuReport3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReport3ActionPerformed(evt);
            }
        });
        jMenu1.add(menuReport3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuReport2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReport2ActionPerformed
        Report2 newWindow = new Report2(this, true);
        newWindow.setVisible(true);
    }//GEN-LAST:event_menuReport2ActionPerformed

    private void menuReport3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReport3ActionPerformed
        Report3 newWindow = new Report3(this, true);
        newWindow.setVisible(true);
    }//GEN-LAST:event_menuReport3ActionPerformed

    private void menuReport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReport1ActionPerformed
        Report1 newWindow = new Report1(this, true);
        newWindow.setVisible(true);
    }//GEN-LAST:event_menuReport1ActionPerformed

    private void menuInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInsertActionPerformed
        restart();
    }//GEN-LAST:event_menuInsertActionPerformed

    private void inputIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIDActionPerformed

    private void inputNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNameActionPerformed

    private void inputAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAgeActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        addPlayer();
    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertPlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertPlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertPlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertPlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertPlayers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JComboBox<String> cbFortitude;
    private javax.swing.JComboBox<String> cbProfile;
    private javax.swing.JComboBox<String> cbTeams;
    private com.toedter.calendar.JDateChooser dateDebutDate;
    private javax.swing.JTextField inputAge;
    private javax.swing.JTextField inputID;
    private javax.swing.JTextField inputName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu menuInsert;
    private javax.swing.JMenuItem menuReport1;
    private javax.swing.JMenuItem menuReport2;
    private javax.swing.JMenuItem menuReport3;
    private javax.swing.JRadioButton radioBtnState;
    // End of variables declaration//GEN-END:variables
}
