package Presentation;

import Bussiness.PlayerManager;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;


public class Report2 extends javax.swing.JDialog {

    private PlayerManager playerMan = new PlayerManager();
    
    public Report2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        
        btnConfirm.setOpaque(true);
    }

    public void restart() {
        Date date = playerMan.restartDate();
        dateInitialDate.setDate(date);
        dateFinalDate.setDate(date);
    }
    
    
    public void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tbData.getModel();
        model.setRowCount(0);
        HashMap<Integer, HashMap> reporte = playerMan.report2(dateInitialDate.getDate(), dateFinalDate.getDate());
        Object[] fill = new Object[3];
        for (Object key : reporte.keySet() ) {
            fill[0] = reporte.get(key).get("Name");
            fill[1] = reporte.get(key).get("Team");
            fill[2] = reporte.get(key).get("Debut");
            model.addRow(fill);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbData = new javax.swing.JTable();
        dateInitialDate = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        dateFinalDate = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuInsert = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        menuReport1 = new javax.swing.JMenuItem();
        menuReport2 = new javax.swing.JMenuItem();
        menuReport3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Hiragino Sans", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(20, 20, 20));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Bienvenido al reporte 2");
        jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 900, -1));

        tbData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Equipo", "Fecha Debut"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbData.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbData);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 630, 320));

        dateInitialDate.setBackground(new java.awt.Color(204, 204, 204));
        dateInitialDate.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(dateInitialDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 180, 40));

        jLabel2.setFont(new java.awt.Font("Hiragino Sans", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(20, 20, 20));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Fecha inicio");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 150, -1));

        dateFinalDate.setBackground(new java.awt.Color(204, 204, 204));
        dateFinalDate.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(dateFinalDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 180, 40));

        jLabel3.setFont(new java.awt.Font("Hiragino Sans", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(20, 20, 20));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Fecha final");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 150, -1));

        btnConfirm.setBackground(new java.awt.Color(0, 153, 153));
        btnConfirm.setFont(new java.awt.Font("Hiragino Sans", 0, 18)); // NOI18N
        btnConfirm.setForeground(new java.awt.Color(0, 0, 0));
        btnConfirm.setText("Confirmar");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 180, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 560));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(245, 245, 245));
        jLabel1.setText("Pamela Murillo Anchia");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 130, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 900, 40));

        menuInsert.setText("Insertar");
        menuInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInsertActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuInsert);

        jMenu1.setText("Reportes");

        menuReport1.setText("Velocidad");
        menuReport1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReport1ActionPerformed(evt);
            }
        });
        jMenu1.add(menuReport1);

        menuReport2.setText("Debut");
        menuReport2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReport2ActionPerformed(evt);
            }
        });
        jMenu1.add(menuReport2);

        menuReport3.setText("Activos");
        menuReport3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReport3ActionPerformed(evt);
            }
        });
        jMenu1.add(menuReport3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInsertActionPerformed
        InsertPlayers newWindow = new InsertPlayers();
        newWindow.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuInsertActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        fillTable();
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void menuReport3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReport3ActionPerformed
        Report3 newWindow = new Report3(new JFrame(), true);
        newWindow.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuReport3ActionPerformed

    private void menuReport2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReport2ActionPerformed

    }//GEN-LAST:event_menuReport2ActionPerformed

    private void menuReport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReport1ActionPerformed
        Report1 newWindow = new Report1(new JFrame(), true);
        newWindow.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuReport1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Report2 dialog = new Report2(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private com.toedter.calendar.JDateChooser dateFinalDate;
    private com.toedter.calendar.JDateChooser dateInitialDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JMenu menuInsert;
    private javax.swing.JMenuItem menuReport1;
    private javax.swing.JMenuItem menuReport2;
    private javax.swing.JMenuItem menuReport3;
    private javax.swing.JTable tbData;
    // End of variables declaration//GEN-END:variables
}
