package Presentation;

import Bussiness.PlayerManager;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;


public class Report3 extends javax.swing.JDialog {

    private PlayerManager playerMan = new PlayerManager();

    public Report3(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        btnConfirm.setOpaque(true);
        
        fillComboBox();
    }
    
    public int isInteger(String numberString) {
        try {
            return Integer.parseInt(numberString); 
        } catch (NumberFormatException e) {
            return -1;
        }
    }


    public void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tbData.getModel();
        model.setRowCount(0);
        HashMap<Integer, HashMap> reporte = playerMan.report3(Integer.parseInt(inputLowerAge.getText()), Integer.parseInt(inputUpperAge.getText()), cbTeams.getSelectedItem().toString());
        Object[] fill = new Object[3];
        for (Object key : reporte.keySet() ) {
            fill[0] = reporte.get(key).get("Name");
            fill[1] = reporte.get(key).get("Age");
            fill[2] = reporte.get(key).get("Debut");
            model.addRow(fill);
        }
    }
    
    public void fillComboBox() {
        ArrayList<String> filling = playerMan.getTeams();
        for (int item = 0; filling.size() > item; item++) {
            cbTeams.addItem(filling.get(item).toString());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbData = new javax.swing.JTable();
        cbTeams = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        inputUpperAge = new javax.swing.JTextField();
        inputLowerAge = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuInsert = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        menuReport1 = new javax.swing.JMenuItem();
        menuReport2 = new javax.swing.JMenuItem();
        menuReport3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Hiragino Sans", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(20, 20, 20));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Bienvenido al reporte 3");
        jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 900, -1));

        jLabel2.setFont(new java.awt.Font("Hiragino Sans", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(20, 20, 20));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Edad inicial");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Hiragino Sans", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(20, 20, 20));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Edad final");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 100, -1));

        tbData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Edad", "Fecha Debut"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbData.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbData);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 630, 320));

        cbTeams.setBackground(new java.awt.Color(204, 204, 204));
        cbTeams.setFont(new java.awt.Font("Hiragino Sans", 0, 18)); // NOI18N
        cbTeams.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(cbTeams, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 180, 40));

        jLabel10.setFont(new java.awt.Font("Hiragino Sans", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(20, 20, 20));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Equipos");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 90, -1));

        btnConfirm.setBackground(new java.awt.Color(0, 153, 153));
        btnConfirm.setFont(new java.awt.Font("Hiragino Sans", 0, 18)); // NOI18N
        btnConfirm.setForeground(new java.awt.Color(0, 0, 0));
        btnConfirm.setText("Confirmar");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 180, 40));

        inputUpperAge.setBackground(new java.awt.Color(204, 204, 204));
        inputUpperAge.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        inputUpperAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputUpperAgeActionPerformed(evt);
            }
        });
        jPanel1.add(inputUpperAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 180, 40));

        inputLowerAge.setBackground(new java.awt.Color(204, 204, 204));
        inputLowerAge.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        inputLowerAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputLowerAgeActionPerformed(evt);
            }
        });
        jPanel1.add(inputLowerAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 180, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 560));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(245, 245, 245));
        jLabel1.setText("Pamela Murillo Anchia");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 130, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 900, 40));

        menuInsert.setText("Insertar");
        menuInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInsertActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuInsert);

        jMenu1.setText("Reportes");

        menuReport1.setText("Velocidad");
        menuReport1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReport1ActionPerformed(evt);
            }
        });
        jMenu1.add(menuReport1);

        menuReport2.setText("Debut");
        menuReport2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReport2ActionPerformed(evt);
            }
        });
        jMenu1.add(menuReport2);

        menuReport3.setText("Activos");
        menuReport3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReport3ActionPerformed(evt);
            }
        });
        jMenu1.add(menuReport3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInsertActionPerformed
        InsertPlayers newWindow = new InsertPlayers();
        newWindow.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuInsertActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        if (isInteger(inputLowerAge.getText()) != -1 && isInteger(inputUpperAge.getText()) != -1) {
            fillTable();
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void inputUpperAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputUpperAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputUpperAgeActionPerformed

    private void inputLowerAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputLowerAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputLowerAgeActionPerformed

    private void menuReport3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReport3ActionPerformed

    }//GEN-LAST:event_menuReport3ActionPerformed

    private void menuReport2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReport2ActionPerformed
        Report2 newWindow = new Report2(new JFrame(), true);
        newWindow.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuReport2ActionPerformed

    private void menuReport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReport1ActionPerformed
        Report1 newWindow = new Report1(new JFrame(), true);
        newWindow.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuReport1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Report3 dialog = new Report3(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JComboBox<String> cbTeams;
    private javax.swing.JTextField inputID;
    private javax.swing.JTextField inputID1;
    private javax.swing.JTextField inputLowerAge;
    private javax.swing.JTextField inputUpperAge;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JMenu menuInsert;
    private javax.swing.JMenuItem menuReport1;
    private javax.swing.JMenuItem menuReport2;
    private javax.swing.JMenuItem menuReport3;
    private javax.swing.JTable tbData;
    // End of variables declaration//GEN-END:variables
}
